name: Testing

on:
  push

jobs:
  test_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust Python version as needed

      - name: Install Django
        run: |
          python3 -m pip install --upgrade pip
          pip install django

      - name: Run Django unit tests
        run: python3 manage.py test
